# Module one: Intro to Data, Data Science & python programming basics part 2

### Course: Data Science
### Week: 2
### Instructor: Eddie

### FILE HANDLING
File handling allows us to:

Store data
Retrieve data
Work with datasets

#### Real-Life Example

CSV datasets, logs, user data  all stored in files.

In [1]:
# Example
# Write to a file
file = open("data.txt", "w")
file.write("Hello World")
file.close()

In [2]:
# Read from a file
file = open("data.txt", "r")
print(file.read())
file.close()

Hello World

In [3]:
with open("data.txt", "r") as file:
    content = file.read()
    print(content)

Hello World

In [8]:
import csv

with open("eddie.csv", "r") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['Customer', 'Usage', 'Churn']
['A', '100', '0']
['B', '50', '1']
['C', '10', '1']
['D', '80', '0']

In [6]:
import pandas as pd

data = {
    "Customer": ["A", "B", "C", "D"],
    "Usage": [100, 50, 10, 80],
    "Churn": [0, 1, 1, 0]
}

df = pd.DataFrame(data)
df

  Customer  Usage  Churn
0        A    100      0
1        B     50      1
2        C     10      1
3        D     80      0

In [7]:
df.to_csv("eddie.csv", index=False)

In [8]:
df_new = pd.read_csv("data.csv")
df_new

  Customer  Usage  Churn
0        A    100      0
1        B     50      1
2        C     10      1
3        D     80      0

In [9]:
import csv

with open("data.csv", "r") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['Customer', 'Usage', 'Churn']
['A', '100', '0']
['B', '50', '1']
['C', '10', '1']
['D', '80', '0']

### EXCEPTION HANDLING
Errors = inevitable
because they know errors are inevitable **EXCEPTION HANDLING** is created to avoid errors that might cause problems for your software or hardware

In [10]:
# Example 
try:
    x = int("abc")
except:
    print("Error occurred")

Error occurred

In [9]:
x= int("abc")

ValueError: invalid literal for int() with base 10: 'abc'

In [12]:
#Specific Exceptions very good for trobleshooting or debegging
try:
    num = int(input("Enter number: "))
    print(10 / num)
except ZeroDivisionError:
    print("Cannot divide by zero")
except ValueError:
    print("Invalid input")

Enter number:  0

Cannot divide by zero

In [11]:
# Custom Exception

def withdraw(amount):
    if amount > 1000:
        raise Exception("Insufficient funds")

try:
    withdraw(2000)
except Exception as e:
    print(e)

Insufficient funds

### REGULAR EXPRESSIONS
Most Useful Regular Expressions (Regex)
|  Expression |  Meaning                        |  Example        |  Matches          |
| ------------- | --------------------------------- | ----------------- | ------------------ |
| `\d`          | Any digit (0–9)                   | `"Age: 25"`       | `2, 5`             |
| `\d+`         | One or more digits                | `"123 apples"`    | `123`              |
| `\D`          | Non-digit                         | `"A1B"`           | `A, B`             |
| `\w`          | Word character (a-z, A-Z, 0-9, _) | `"user_1"`        | `u, s, e, r, _, 1` |
| `\w+`         | One or more word characters       | `"user_123"`      | `user_123`         |
| `\W`          | Non-word character                | `"hello!"`        | `!`                |
| `\s`          | Whitespace (space, tab)           | `"Hello World"`   | space              |
| `\s+`         | One or more spaces                | `"Hello   World"` | spaces             |
| `\S`          | Non-whitespace                    | `"Hi there"`      | `H, i, t, h...`    |
| `\S+`         | Continuous non-space text         | `"hello world"`   | `hello`, `world`   |



Common Real-World Patterns

|  Expression |  Meaning             |  Example         |  Matches        |
| ------------- | ---------------------- | ------------------ | ---------------- |
| `r"\S+@\S+"`  | Simple email pattern   | `"test@gmail.com"` | `test@gmail.com` |
| `r"\d{3}"`    | Exactly 3 digits       | `"1234"`           | `123`            |
| `r"\d{2,4}"`  | Between 2 and 4 digits | `"2025"`           | `2025`           |
| `r"[a-z]"`    | Lowercase letters      | `"abc"`            | `a, b, c`        |
| `r"[A-Z]"`    | Uppercase letters      | `"ABC"`            | `A, B, C`        |
| `r"[a-zA-Z]"` | Any letter             | `"Hello"`          | `H, e, l...`     |
| `r"[0-9]"`    | Digits (same as `\d`)  | `"456"`            | `4, 5, 6`        |

In [12]:
# Example 
import re

text = "Contact: user123@gmail.com, Age: 25"

# Extract email
email = re.findall(r"\S+@\S+", text)

# Extract numbers
numbers = re.findall(r"\d+", text)

print("Email:", email)
print("Numbers:", numbers)

Email: ['user123@gmail.com,']
Numbers: ['123', '25']

## APIs (REAL-WORLD DATA SOURCE)

In [13]:
import requests

response = requests.get("https://api.github.com")
print(response.status_code)

200

In [14]:
data = response.json()
print(data["current_user_url"])

https://api.github.com/user

In [14]:
import requests

url = "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd"

response = requests.get(url)

print(response.status_code)

data = response.json()
print(data)

200
{'bitcoin': {'usd': 72922}}

### DATABASES

In [16]:
import sqlite3

conn = sqlite3.connect("test.db")
cursor = conn.cursor()

cursor.execute("CREATE TABLE Student_record (name TEXT, age INTEGER)")

In [17]:
cursor.execute("INSERT INTO student_record VALUES ('Alice', 30)")
conn.commit()

In [19]:
cursor.execute("SELECT * FROM student_record")
rows = cursor.fetchall()

for row in rows:
    print(row)

('Alice', 30)

### FUNCTIONS

In [22]:
def add(a, b):
    return a + b
add(40,30)

70

In [21]:

a= 40
b =30
c= a + b
print(c)

70

In [23]:
add(10,40)

50

In [24]:
def greet(name="Eddie"):
    return f"Hello , {name}"

In [25]:
greet()

'Hello , Eddie'

### Object-Oriented Programming

Definition:

OOP is a way of programming where you organize code using objects and classes.

Class (Blueprint)

A class is like a template.

In [31]:
class Car:
    pass

### Object (Real Instance)

An object is a real thing created from a class.

In [32]:
my_car = Car()

Analogy:

Class = House plan 

Object = Real house

## Attributes (Properties)

These are variables inside a class.

In [36]:
# Example
class Student:
    def __init__(self, name, age):
        self.name=name
        self.age=age

In [37]:
s1=Student("Eddie", 60)
print("My name is : ", s1.name)

My name is :  Eddie

## The End